### ISSUE TITLE
save_h5 code is missing

### ISSUE THREAD

**Issue by KumarAshitabh** [faroukmokhtar/ImageSegmentationPASCAL#1]
Hi, 
I am unable to find implementation for function save_h5

**Comment by farakiko** [comment]
hi,
I don't think we needed it in the end so i don't know anything about it

**Comment by KumarAshitabh** [comment]
sure , np 
I added this function for saving h5 into local system

def save_h5(path,images,labels):
    """Save data as a HDF5 file.
    """
    with h5py.File(path, 'w') as f:
      f['images'] = images
      f['labels'] = labels
